### PR TITLE
Groovy updates

### PR DESCRIPTION
**Pull request by fmessmer**
This pull request (together with the pull requests for cob_robots and cob_simulation) fix Ticket #562 http://care-o-bot.org/trac/ticket/562

It also brings the environments supported in electric to groovy

### CODE REVIEW

**Comment by abubeck** [comment]
Wow, lots of commits are part of this pull request, which have nothing to do with the navigation goals. 
Is this on purpose or an accident?

**Comment by fmessmer** [comment]
see -> It also brings the environments supported in electric to groovy ;-)

I merged cob_environments electric_dev to clean up the stack and only have the environments that should be supported (ipa-appartment, ipa-maze, ipa-factory...)

However, ipa-maze and ipa-factory are not working yet - I'm workin on it

**Comment by fmessmer** [comment]
One question here:

What about fuerte?
Will we need to support all this in fuerte as well?

**Comment by abubeck** [comment]
Only if someone still depends on fuerte (hopefully not). If thats really the case we can port to fuerte later.
I think groovy should be fine for now.
I will merge the pull request if maze and apartment are working, just keep me updated.
Thanks for the cleanup !!

**Comment by fmessmer** [comment]
I compared the pull_request #19 with this one. all changes from #19 are included in this one as well. Thus you can just use this one (it includes some more fixes as to sdf 1.3 format)

However, ipa-maze and ipa-factory are still not working!
Should they be removed from cob_environments and re-added once they are working under groovy?
I could delete them just on the groovy_updates feature branch.

**Comment by abubeck** [comment]
Ok, you are right. Just delete them for now and we will add them again later. As long as apartment is working.
After deletion I will merge the pull request.

**Comment by fmessmer** [comment]
Alright, I cleaned up cob_environments now!
supported environments are now:
- empty
- ipa-kitchen
- ipa-apartment
- ipa-factory

ipa-maze has been removed

**Pull request merged**
