### PR TITLE
dummy files for new simulation environment: ipa_production_plant

### PR DESCRIPTION
**Pull request by stefandoerr**

### CODE REVIEW

**Comment by floweisshardt** [comment]
LGTM, merge together with https://github.com/ipa320/cob_simulation/pull/98

**Comment by NadiaHG** [comment]
LGTM

**Comment by fmessmer** [comment]
This should not be merged until the comments in https://github.com/ipa320/cob_simulation/pull/98 are considered...

**Comment by fmessmer** [comment]
This PR is obsolete and **should not be merged** as I significantly cleaned it up and rebased it to latest ipa320/indigo_dev in #103

**Comment by fmessmer** [comment]
all comments considered in #103 ...thus closing this PR unmerged

**Pull request closed without merging**
