### PR TITLE
Navigation maps

### PR DESCRIPTION
**Pull request by stefandoerr**
As discussed with @ipa-frm. It would make sense to integrate the navigation maps into the main branch. The maps basically consist of yaml files defining feature and path maps for localization and path planning

### CODE REVIEW

**Comment by floweisshardt** [comment]
I'd only like to merge the maps for our default environments which are empty, ipa-apartment, ipa-factory, ipa-kitchen.
There is a simple reason for that: If we add additional environments, we should fully support them which includes gazebo simulation, default_env_config, etc for all robots! There is already a lot of effort necessary to support all robots in the four environments we have.

**Comment by stefandoerr** [comment]
Ok. So we keep draging our navigation-branch along where we put all this stuff or what would you suggest?

**Comment by floweisshardt** [comment]
This is one possibility. 

Another (better) one would be to use ipa-factory which is to my knowledge not actively used anymore. You could just integrate your environment there. If so, please make sure that there is a simulation available too (See https://github.com/ipa320/cob_simulation/tree/indigo_dev/cob_gazebo_worlds).

**Comment by stefandoerr** [comment]
We don't have simulations for all our real world environments. ipa-factory is one of these as well as ipa-office. Theses environments are used for real world tests.

**Comment by floweisshardt** [comment]
Could you build up a simulation? There is also a way to spawn a gazebo environment based on an existing map which basically spawns walls for all black Pixels in the map. Would that be an option?

**Comment by fmessmer** [comment]
ipa-factory is using that approach (i.e. heightmap)

**Comment by stefandoerr** [comment]
Building up a simulation for all environments is out of scope. 2nd option sounds ok if it is not too much work.

**Comment by fmessmer** [comment]
@ipa-fmw So what are we going to do about this?
@ipa-srd what about your new simulation environment?

I'm perfectly fine having another environment in cob_gazebo_worlds....as I see the need for something more industrial for navigation tests....and it is not much of an effort to maintain it....I can do it....and the new envrionment will be used by many students, too....from my point of view it is better to add it to ipa320/indigo_dev than dragging a parallel universe on the side....

**Comment by stefandoerr** [comment]
The code is currently on different branches of my fork. I’m waiting till this issue is cleared and I can do the PRs to the goal branch.

Von: Felix Messmer [mailto:notifications@github.com]
Gesendet: Freitag, 30. Oktober 2015 15:33
An: ipa320/cob_environments
Cc: Dörr, Stefan
Betreff: Re: [cob_environments] Navigation maps (#92)

@ipa-fmwhttps://github.com/ipa-fmw So what are we going to do about this?
@ipa-srdhttps://github.com/ipa-srd what about your new simulation environment?

I'm perfectly fine having another environment in cob_gazebo_worlds....as I see the need for something more industrial for navigation tests....and it is not much of an effort to maintain it....I can do it....and the new envrionment will be used by many students, too....from my point of view it is better to add it to ipa320/indigo_dev than dragging a parallel universe on the side....

**Comment by floweisshardt** [comment]
if we fully support the new environment also in simulation and all configs (including navigation and dashbaord) it is OK for me

**Comment by fmessmer** [comment]
As @ipa-srd explained today, the feature maps are optional and will not lead to test failure...

Before merging this PR, customer specific environments should be removed, i.e. `adblab` and `agv-testenv`.
Regarding `ipa-office`, we could try to create a gazebo model from the heightmap (map.png)...however this is not just straight forward and requires a bit more work...still I'd be ok adding the feature maps for this environment. Btw, what's the difference between `ipa-office` and `ipa-office-unmapped`? Is the "unmapped" version a predecessor and thus obsolete?

**Pull request merged**
