### PR TITLE
Added loc map functionality

### PR DESCRIPTION
**Pull request by stefandoerr**

### CODE REVIEW

**Comment by floweisshardt** [comment]
for what is this file used for? why not using `map.yaml` directly?

**Comment by stefandoerr** [comment]
We have environments where we need two separated maps, one for move_base one for localization. This is due to the fact, that the localization needs the environment to look like it appears in the scanner whereas move base needs information about occupied (permitted) and free space. Therefore we introduced the `loc_map.yaml` which points to a `loc_map.png` and this is what the localization (i.e. long_term_slam) is searching for. In environments where you don' t need two maps, you just create a symlink -> this PR

**Review by jabbenseth — APPROVED** [review]
to use different maps for planning and localization the new "loc_map" is added. We have environments/applications where this is the case. We decided on having symlinks here to show the possibility

**Review by floweisshardt — APPROVED** [review]
ok, fine for me.

**Pull request merged**
