### PR TITLE
iff-versuchshalle environment

### PR DESCRIPTION
**Pull request by mgruhler**
@ipa-fmw what is the policy here? Can we add environments only when there is a simulation env as well? If yes, this need to go somewhere else.

@ipa-flg I'm not quite sure, which state this is. Should we keep this? Should we put this in another repo?

Please only merge when both, @ipa-fmw and @ipa-flg approve this PR.

### CODE REVIEW

**Comment by ipa-flg** [comment]
@ipa-mig given state is quite old. I am not sure how valid it is and whether we are ever going to be able to set up the same exact scenario again. 

Also identification is not specific enough, as this was a "lasermarker only" testbed, and there are more scenarios in IFF. 

We also should think about checking in the latest IFF setup in terms of the application center. There are still open branches here https://github.com/ipa-flg/cob_environments/tree/application-center-demo and here https://github.com/ipa-jba/cob_environments/tree/application-center-demo as well as
https://github.com/ipa-jba/cob_environments/tree/automatica-demo

As there aren't any simulations available, and as these are rather testbeds/demo cases, we should move them somewhere else, but definitely store them.

Any ideas how to do that without messing up our launch-file structure?

**Review by floweisshardt — CHANGES_REQUESTED** [review]
we should not add any enrionment we're using our robots in into cob_environments. We once agreed that the cob_default_env_config (it says **default**) only hold a small set of commonly used environments which are also supported in simulation for testing.

If there are additional environments (non default), especially for temporary demos, it is best practice to setup up a demo package which includes environment  (and robot) specific files. In cob_bringup all launch files are setup in a way that you can easily parse in a new environment_config (pkg_env_config) or robot_config (pkg_hardware_config) package and parse that by launch file arguments.

I therefore vote to not merge this but create a separate iff_demo package in a navigation_demo repository (probably requires navigation_bringup cleanup with proper launch files arguments before).

**Comment by mgruhler** [comment]
@ipa-fmw thanks. Actually, we discussed the same thing yesterday. This PR was mainly to get the discussion started ;-)

I'll keep this PR open a few more days until we know how to resolve this.

**Comment by floweisshardt** [comment]
@ipa-mig: you're welcome. I'd like to offer my advice if needed. Let me know.

**Comment by mgruhler** [comment]
@ipa320/navigation-push Ping How to proceed here?

**Comment by jabbenseth** [comment]
we can move everything here to https://github.com/ipa320/ipa_navigation_demos easy solution, compatible with the intention of creating the repo and the intention of `cob_default_env_config`.

**Pull request closed without merging**
