### PR TITLE
adapt to new yaml layout of spawn_object script

### PR DESCRIPTION
**Pull request by floweisshardt**
config changes required for https://github.com/ipa320/cob_simulation/pull/167

### CODE REVIEW

**Review by fmessmer — COMMENTED** [review]
can you do the same for our `msh` and `hdg` repos, i.e. persons etc.

**Comment by floweisshardt** [comment]
done for msh in https://github.com/mojin-robotics/msh/pull/218
done for hdg in https://github.com/mojin-robotics/hdg/pull/69

**Comment by fmessmer** [comment]
I will rebase and retarget this PR after https://github.com/ipa320/cob_simulation/pull/168 is merged

**Review by fmessmer — CHANGES_REQUESTED** [review]
I will rebase when merging the cob_simulation prs

**Review by fmessmer — APPROVED** [review]

**Pull request merged**
