### PR TITLE
updated map for ipa-apartment

### PR DESCRIPTION
**Pull request by ipa-jcl-cs**
New recorded map for the ipa-apartment.
Current one is slightly rotated, doesn't contains the walls in the lower right room and has one small hallway which doesn't exist anymore.
The content of the map.yaml file of the new recorded map is exactly the same - therefore just one changed file.

### CODE REVIEW

**Review by fmessmer — CHANGES_REQUESTED** [review]
what `ipa-apartment` are you talking about? where on campus did you record the map?
or was this recorded in simulation?

please post screenshots of before and after to clarify what has changed...

**Review by floweisshardt — CHANGES_REQUESTED** [review]
I agree that it's a little ugly that the map frame is not alligned with the walls. But I'd rather not merge this as it will break all nav goals ever teached for the ipa-apartment. For what reason can you __not__ use the map as it is?

**Comment by ipa-jcl-cs** [comment]
The recording of the map is done in the simulation. The now used static map doesn't align with the simulation.
simulation of ipa-apartment in gazebo

Map is rotated, doesn't contain additional walls and has one extra hallway 
currently used map (converted from pgm to png for upload)

Map of PR: No rotation, contains additional walls in lower right room and doesn't include the small extra hallway.
map of PR

**Comment by ipa-jcl-cs** [comment]
@floweisshardt 
For myself I'm going to use the new recorded map as the laserscan-data of the simulation show that there are additional walls, which are not shown in the static map (loaded from map.pgm). Therefore the scan-matching between map and scan (derived from the gazebo-simulation) doesn't perform well.

**Comment by fmessmer** [comment]
Option 1:
 - new map contains new walls, but does not change the map origin

Option 2:
 - remove the walls missing in the map from ipa-apartment.urdf

**Comment by ipa-jcl-cs** [comment]
Thanks for the suggestions, but creating a rotated map on purpose is probably not that easy. 
Another option may would be to write a script to rotate all objects and segments specified in the corresponding yaml-files. But I won't do this in the moment. Therefore I close the PR.

**Comment by stefandoerr** [comment]
Thanks @ipa-jcl-cs for providing the PR. The rotational offset has been in there for way too long. There are six nav goals defined in the environment. Checking if these are still accessible and roughly are located in the area where they should be, shouldn't be that much effort. Would be a pity to reject the nice map that you recorded just because of these

**Pull request closed without merging**
